{% set name = "sas7bdat" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed8bfe652c7e8bb8e8db788da5680fdbe1dada2361ee00fb7eeda032e7388f3d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.8.0

test:
  source_files:
    - tests
  imports:
    - sas7bdat
  requires:
    - python
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://pyhacker.com/pages/sas7bdat.html
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: sas7bdat file reader for Python
  description: |
    sas7bdat will read sas7bdat files using pure Python (2.6+, 3+). No SAS
    software required!
  doc_url: https://pypi.org/pypi/sas7bdat
  dev_url: https://bitbucket.org/jaredhobbs/sas7bdat
